Traceback (most recent call last):
  File "/Users/simonmartin/mambaforge/envs/mpp001/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/simonmartin/mambaforge/envs/mpp001/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simonmartin/mambaforge/envs/mpp001/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simonmartin/mambaforge/envs/mpp001/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/simonmartin/mambaforge/envs/mpp001/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/simonmartin/mambaforge/envs/mpp001/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/simonmartin/mambaforge/envs/mpp001/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
colours = ['red','green','blue']
for colour in colours:
    print(f'{colour})
------------------


[0;36m  Cell [0;32mIn[1], line 3[0;36m[0m
[0;31m    print(f'{colour})[0m
[0m          ^[0m
[0;31mSyntaxError[0m[0;31m:[0m unterminated string literal (detected at line 3)


